name: Build/Test Servy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build Servy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup magic-nix-cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build servy
        run: |
          nix build .#servy

      - name: Run tests
        run: |
          nix develop --command cargo test -- --show-output
